export var Energy = {

    dBodyAddForce: Module.cwrap('dBodyAddForce', '', ['number', 'number', 'number', 'number']),
    dBodyAddRelForce: Module.cwrap('dBodyAddRelForce', '', ['number', 'number', 'number', 'number']),
    dBodyAddRelTorque: Module.cwrap('dBodyAddRelTorque', '', ['number', 'number', 'number', 'number']),
    dBodyAddTorque: Module.cwrap('dBodyAddTorque', '', ['number', 'number', 'number', 'number']),
    dBodyCreate: Module.cwrap('dBodyCreate', 'number', ['number']),
    dBodyDestroy: Module.cwrap('dBodyDestroy', '', ['number']),
    dBodyDisable: Module.cwrap('dBodyDisable', '', ['number']),
    dBodyEnable: Module.cwrap('dBodyEnable', '', ['number']),
    dBodyGetAngularVel: Module.cwrap('dBodyGetAngularVel', 'number', ['number']),
    dBodyGetForce: Module.cwrap('dBodyGetForce', 'number', ['number']),
    dBodyGetLinearVel: Module.cwrap('dBodyGetLinearVel', 'number', ['number']),
    dBodyGetPosition: Module.cwrap('dBodyGetPosition', 'number', ['number']),
    dBodyGetQuaternion: Module.cwrap('dBodyGetQuaternion', 'number', ['number']),
    dBodyGetTorque: Module.cwrap('dBodyGetTorque', 'number', ['number']),
    dBodyIsEnabled: Module.cwrap('dBodyIsEnabled', 'number', ['number']),
    dBodySetAngularVel: Module.cwrap('dBodySetAngularVel', '', ['number', 'number', 'number', 'number']),
    dBodySetAutoDisableAngularThreshold: Module.cwrap('dBodySetAutoDisableAngularThreshold', '', ['number', 'number']),
    dBodySetAutoDisableAverageSamplesCount: Module.cwrap('dBodySetAutoDisableTime', '', ['number', 'number']),
    dBodySetAutoDisableFlag: Module.cwrap('dBodySetAutoDisableFlag', '', ['number', 'number']),
    dBodySetAutoDisableLinearThreshold: Module.cwrap('dBodySetAutoDisableLinearThreshold', '', ['number', 'number']),
    dBodySetAutoDisableTime: Module.cwrap('dBodySetAutoDisableTime', '', ['number', 'number']),
    dBodySetFiniteRotationMode: Module.cwrap('dBodySetFiniteRotationMode', '', ['number', 'number']),
    dBodySetGyroscopicMode: Module.cwrap('dBodySetGyroscopicMode', '', ['number', 'number']),
    dBodySetForce: Module.cwrap('dBodySetForce', '', ['number', 'number', 'number', 'number']),
    dBodySetLinearVel: Module.cwrap('dBodySetLinearVel', '', ['number', 'number', 'number', 'number']),
    dBodySetMass: Module.cwrap('dBodySetMass', '', ['number', 'number']),
    dBodyGetMass: Module.cwrap('dBodyGetMass', '', ['number', 'number']),
    dBodySetPosition: Module.cwrap('dBodySetPosition', '', ['number', 'number', 'number', 'number']),
    dBodySetQuaternion: Module.cwrap('dBodySetQuaternion', '', ['number', 'number']),
    dBodySetRotation: Module.cwrap('dBodySetRotation', '', ['number', 'number']),
    dBodySetTorque: Module.cwrap('dBodySetTorque', '', ['number', 'number', 'number', 'number']),
    dBodyGetDxFlags: Module.cwrap('dBodyGetDxFlags', 'number', ['number']),
    dBodyGetFlags: Module.cwrap('dBodyGetFlags', 'number', ['number']),
    dBodySetFlags: Module.cwrap('dBodySetFlags', '', ['number', 'number']),
    dBodySetNotification_interval: Module.cwrap('dBodySetNotification_interval', '', ['number', 'number']),
    
    dCreateBox: Module.cwrap('dCreateBox', 'number', ['number', 'number', 'number', 'number']),
    dCreateCylinder: Module.cwrap('dCreateCylinder', 'number', ['number', 'number']),
    dCreateHeightfield: Module.cwrap('dCreateHeightfield', 'number', ['number', 'number', 'number']),
    dCreatePlane: Module.cwrap('dCreatePlane', 'number', ['number', 'number', 'number', 'number', 'number']),
    dCreateSphere: Module.cwrap('dCreateSphere', 'number', ['number', 'number']),
    dCreateTriMesh: Module.cwrap('dCreateTriMesh', 'number', ['number', 'number', 'number', 'number', 'number']),
    dCreateRay: Module.cwrap("dCreateRay", "number", ['number', 'number']),
    dGeomRaySet: Module.cwrap("dGeomRaySet", "", ['number', 'number', 'number', 'number', 'number', 'number', 'number']),
    dGeomDestroy: Module.cwrap('dGeomDestroy', '', ['number']),
    dGeomGetMaterial: Module.cwrap('dGeomGetMaterial', 'number', ['number']),
    dGeomGetPosition: Module.cwrap('dGeomGetPosition', 'number', ['number']),
    dGeomGetQuaternion: Module.cwrap('dGeomGetQuaternion', '', ['number', 'number']),
    dGeomHeightfieldDataBuildDouble: Module.cwrap('dGeomHeightfieldDataBuildDouble', '', ['number', 'number', 'number', 'number', 'number', 'number', 'number', 'number', 'number', 'number', 'number', 'number']),
    dGeomHeightfieldDataCreate: Module.cwrap('dGeomHeightfieldDataCreate', 'number', []),
    dGeomHeightfieldDataSetBounds: Module.cwrap('dGeomHeightfieldDataSetBounds', '', ['number', 'number', 'number']),
    dGeomSetBody: Module.cwrap('dGeomSetBody', '', ['number', 'number']),
    dGeomSetMaterial: Module.cwrap('dGeomSetMaterial', '', ['number', 'number']),
    dGeomSetMotionVector: Module.cwrap('dGeomSetMotionVector', '', ['number', 'number']),
    dGeomSetOffsetPosition: Module.cwrap('dGeomSetOffsetPosition', '', ['number', 'number', 'number']),
    dGeomSetPosition: Module.cwrap('dGeomSetPosition', '', ['number', 'number', 'number', 'number']),
    dGeomSetQuaternion: Module.cwrap('dGeomSetQuaternion', '', ['number', 'number']),
    dGeomTriMeshDataBuildSingle: Module.cwrap('dGeomTriMeshDataBuildSingle', '', []),
    dGeomTriMeshDataCreate: Module.cwrap('dGeomTriMeshDataCreate', 'number', []),

    getGeomsCollisionData: Module.cwrap('getGeomsCollisionData', 'number', []),
    getGeomsCollisionBody: Module.cwrap('getGeomsCollisionBody', 'number', []),
    getGeomsCollisionDataLength: Module.cwrap('getGeomsCollisionDataLength', 'number', []),

    dInitODE2: Module.cwrap('dInitODE2', '', ['number']),
    dInitODE: Module.cwrap('dInitODE', '', []),

    dJointAttach: Module.cwrap('dJointAttach', '', ['number', 'number', 'number']),
    dJointCreateBall: Module.cwrap('dJointCreateBall', 'number', ['number', 'number']),
    dJointCreateHinge2: Module.cwrap('dJointCreateHinge2', 'number', ['number', 'number']),
    dJointCreateHinge: Module.cwrap('dJointCreateHinge', 'number', ['number', 'number']),
    dJointCreateSlider: Module.cwrap('dJointCreateSlider', 'number', ['number', 'number']),
    dJointCreateTransmission: Module.cwrap('dJointCreateTransmission', '', ['number', 'number']),
    dJointCreateAMotor: Module.cwrap('dJointCreateAMotor', '', ['number', 'number']),
    dJointCreateLMotor: Module.cwrap('dJointCreateLMotor', '', ['number', 'number']),
    dJointCreateUniversal: Module.cwrap('dJointCreateUniversal', '', ['number', 'number']),
    dJointCreatePiston: Module.cwrap('dJointCreatePiston', '', ['number', 'number']),
    dJointCreateFixed: Module.cwrap('dJointCreateFixed', '', ['number', 'number']),
    dJointDestroy: Module.cwrap('dJointDestroy', '', ['number']),
    dJointGetHinge2Anchor2: Module.cwrap('dJointGetHinge2Anchor2', '', ['number', 'number']),
    dJointGetHinge2Anchor: Module.cwrap('dJointGetHinge2Anchor', '', ['number', 'number']),
    dJointGetHinge2Angle1: Module.cwrap('dJointGetHinge2Angle1', '', ['number']),
    dJointGetHinge2Axis1: Module.cwrap('dJointGetHinge2Axis1', '', ['number', 'number']),
    dJointGetHinge2Axis2: Module.cwrap('dJointGetHinge2Axis2', '', ['number', 'number']),
    dJointGetHingeAnchor2: Module.cwrap('dJointGetHingeAnchor2', '', ['number', 'number']),
    dJointGetHingeAnchor: Module.cwrap('dJointGetHingeAnchor', '', ['number', 'number']),
    dJointGetHingeAxis: Module.cwrap('dJointGetHingeAxis', '', ['number', 'number']),
    dJointGetHingeAngle: Module.cwrap('dJointGetHingeAngle', 'number', ['number']),
    dJointGetHingeAngleRate: Module.cwrap('dJointGetHingeAngleRate', 'number', ['number']),
    dJointGroupCreate: Module.cwrap('dJointGroupCreate', 'number', ['number']),
    dJointGroupDestroy: Module.cwrap('dJointGroupDestroy', '', ['number']),
    dJointGroupEmpty: Module.cwrap('dJointGroupEmpty', '', ['number']),
    dJointSetBallAnchor: Module.cwrap('dJointSetBallAnchor', '', ['number', 'number', 'number', 'number']),
    dJointSetBallAnchor2: Module.cwrap('dJointSetBallAnchor2', '', ['number', 'number', 'number', 'number']),
    dJointSetBallParam: Module.cwrap('dJointSetBallParam', '', ['number', 'number', 'number']),
    dJointGetBallAnchor: Module.cwrap('dJointGetBallAnchor', '', ['number', 'number']),
    dJointGetBallAnchor2: Module.cwrap('dJointGetBallAnchor2', '', ['number', 'number']),
    dJointSetFeedback: Module.cwrap('dJointSetFeedback', '', ['number', 'number']),
    dJointSetHinge2Anchor: Module.cwrap('dJointSetHinge2Anchor', '', ['number', 'number', 'number', 'number']),
    dJointSetHinge2Axis1: Module.cwrap('dJointSetHinge2Axis1', '', ['number', 'number', 'number', 'number']),
    dJointSetHinge2Axis2: Module.cwrap('dJointSetHinge2Axis2', '', ['number', 'number', 'number', 'number']),
    dJointSetHinge2Param: Module.cwrap('dJointSetHinge2Param', '', ['number', 'number', 'number']),
    dJointSetHingeAnchor: Module.cwrap('dJointSetHingeAnchor', '', ['number', 'number', 'number', 'number']),
    dJointSetHingeAxis: Module.cwrap('dJointSetHingeAxis', '', ['number', 'number', 'number', 'number']),
    dJointSetHingeParam: Module.cwrap('dJointSetHingeParam', '', ['number', 'number', 'number']),
    dJointSetSliderAxis: Module.cwrap('dJointSetSliderAxis', '', ['number', 'number', 'number', 'number']),
    dJointSetSliderParam: Module.cwrap('dJointSetSliderParam', '', ['number', 'number', 'number']),
    dJointSetTransmissionAnchor1: Module.cwrap('dJointSetTransmissionAnchor1', '', ['number', 'number', 'number', 'number']),
    dJointSetTransmissionAnchor2: Module.cwrap('dJointSetTransmissionAnchor2', '', ['number', 'number', 'number', 'number']),
    dJointSetTransmissionAxis1: Module.cwrap('dJointSetTransmissionAxis1', '', ['number', 'number', 'number', 'number']),
    dJointSetTransmissionAxis2: Module.cwrap('dJointSetTransmissionAxis2', '', ['number', 'number', 'number', 'number']),
    dJointSetTransmissionAxis: Module.cwrap('dJointSetTransmissionAxis', '', ['number', 'number', 'number', 'number']),
    dJointSetTransmissionBacklash: Module.cwrap('dJointSetTransmissionBacklash', '', ['number', 'number']),
    dJointSetTransmissionMode: Module.cwrap('dJointSetTransmissionMode', '', ['number', 'number']),
    dJointSetTransmissionRatio: Module.cwrap('dJointSetTransmissionRatio', '', ['number', 'number']),

    dMassAdjust: Module.cwrap('dMassAdjust', '', ['number', 'number']),
    dMassSetBox: Module.cwrap('dMassSetBox', '', ['number', 'number', 'number', 'number']),
    dMassSetCylinder: Module.cwrap('dMassSetCylinder', '', ['number', 'number', 'number', 'number', 'number']),
    dMassSetSphere: Module.cwrap('dMassSetSphere', '', ['number', 'number', 'number']),
    dMassSetTrimesh: Module.cwrap('dMassSetTrimesh', '', ['number', 'number', 'number']),
    dMassTranslate: Module.cwrap('dMassTranslate', '', ['number', 'number', 'number']),
    dMaterialCreate: Module.cwrap('dMaterialCreate', 'number', ['number']),
    dMaterialGetParameter: Module.cwrap('dMaterialGetParameter', 'number', ['number', 'number']),
    dMaterialSetParameter: Module.cwrap('dMaterialSetParameter', '', ['number', 'number', 'number']),
    dRFromAxisAndAngle: Module.cwrap('dRFromAxisAndAngle', '', ['number', 'number', 'number', 'number', 'number']),
    dRFromZAxis: Module.cwrap('dRFromZAxis', '', ['number', 'number', 'number', 'number']),
    dRSetIdentity: Module.cwrap('dRSetIdentity', '', ['number']),
    dAreConnected: Module.cwrap('dAreConnected', 'number', ['number', 'number']),
    dAreConnectedExcluding: Module.cwrap('dAreConnectedExcluding', 'number', ['number', 'number', 'number']),
    dSimpleSpaceCreate: Module.cwrap('dSimpleSpaceCreate', 'number', ['number']),
    dHashSpaceCreate: Module.cwrap('dHashSpaceCreate', 'number', ['number']),
    dHashSpaceSetLevels: Module.cwrap('dHashSpaceSetLevels', '', ['number', 'number', 'number']),

    dSpaceDestroy: Module.cwrap('dSpaceDestroy', '', ['number']),
    dSpaceCollide: Module.cwrap('dSpaceCollide', '', ['number', 'number', 'number']),

    dWorldCreate: Module.cwrap('dWorldCreate', '', ['number']),
    dWorldGetGravity2: Module.cwrap('dWorldGetGravity2', 'number', ['number']),
    dWorldDestroy: Module.cwrap('dWorldDestroy', '', ['number']),
    dWorldGetQuickStepNumIterations: Module.cwrap('dWorldGetQuickStepNumIterations', 'number', ['number']),
    dWorldQuickStep: Module.cwrap('dWorldQuickStep', 'number', ['number', 'number']),
    dWorldSetGravity: Module.cwrap('dWorldSetGravity', '', ['number', 'number', 'number', 'number']),
    dWorldSetQuickStepNumIterations: Module.cwrap('dWorldSetQuickStepNumIterations', '', ['number', 'number']),
    dWorldStep: Module.cwrap('dWorldStep', 'number', ['number', 'number']),
    dWorldSetAutoDisableAverageSamplesCount: Module.cwrap('dWorldSetAutoDisableAverageSamplesCount', '', ['number', 'number']),
    dWorldSetAutoDisableFlag: Module.cwrap('dWorldSetAutoDisableFlag', '', ['number', 'number']),
    dWorldSetAutoDisableLinearThreshold: Module.cwrap('dWorldSetAutoDisableLinearThreshold', '', ['number', 'number']),
    dWorldSetAutoDisableAngularThreshold: Module.cwrap('dWorldSetAutoDisableAngularThreshold', '', ['number', 'number']),
    dWorldSetAutoDisableSteps: Module.cwrap('dWorldSetAutoDisableSteps', '', ['number', 'number']),
    dWorldSetAutoDisableTime: Module.cwrap('dWorldSetAutoDisableTime', '', ['number', 'number']),
    dWorldSetNotificationInterval: Module.cwrap('dWorldSetNotificationInterval', '', ['number', 'number']),
    dWorldSetFlags: Module.cwrap('dWorldSetFlags', '', ['number', 'number']),
    dWorldGetFlags: Module.cwrap('dWorldGetFlags', 'number', ['number']),
    dWorldGetDxFlags: Module.cwrap('dWorldGetDxFlags', 'number', ['number']),
    dWorldSetERP: Module.cwrap('dWorldSetERP', '', ['number', 'number']),
    dWorldSetCFM: Module.cwrap('dWorldSetCFM', '', ['number', 'number']),
    dWorldGetERP: Module.cwrap('dWorldGetERP', 'number', ['number']),
    dWorldGetCFM: Module.cwrap('dWorldGetCFM', 'number', ['number']),

    init: Module.cwrap('init', 'boolean', ['number', 'number', 'number', 'number']),
    setFlagmode: Module.cwrap('setFlagmode', '', ['number']),
    setFlagmode2: Module.cwrap('setFlagmode2', '', ['number']),
    setMaxContact: Module.cwrap('setMaxContact', '', ['number']),
    setTimestep: Module.cwrap('setTimestep', '', ['number', 'number']),
    run: Module.cwrap('run', '', []),
    closeEnergy: Module.cwrap('dCloseODE', '', []),

};